name: Vulnerability Check

on:
  workflow_call:

permissions: {}

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install govulncheck
        env:
          # renovate: datasource=github-releases depName=golang/vuln
          GOVULNCHECK_VERSION: v1.1.4
        run: go install golang.org/x/vuln/cmd/govulncheck@${GOVULNCHECK_VERSION}

      - name: Run govulncheck
        run: govulncheck ./...
